core/urls.py
from django.urls import path, include
from .views import (
    AddToInventoryView,
    DeleteFromInventoryView,
    HomeView,
    ItemDetailView,
    OrderSummaryView,
    AddNewItemView,

    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    landing_page
)

app_name = 'core'

urlpatterns = [
    
    path("", HomeView.as_view(), name="home"),
    path("add-new-item/", AddNewItemView, name="add-new-item"),
    
    path("order-summary/", OrderSummaryView.as_view(), name="order-summary"),
    path("product/<slug>/", ItemDetailView.as_view(), name="product"),
    path("add-to-cart/<slug>", add_to_cart, name="add-to-cart"),
    path("remove-from-cart/<slug>", remove_from_cart, name="remove-from-cart"),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),

    path(
        "add-to-inventory/",
        AddToInventoryView.as_view(),
        name="add-to-inventory"
    ),

    path(
        "delete-from-inventory/",
        DeleteFromInventoryView.as_view(),
        name="delete-from-inventory"
    ),

]

gettingstarted/urls.py
from django.conf import settings
from django.urls import path, include
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    path('',          include('core.urls', namespace='core')),
    path("admin/",    admin.site.urls),
    path('accounts/', include('allauth.urls'))
]

# if settings.DEBUG:
#     import debug_toolbar 
#     urlpatterns += [path('__debug__',include(debug_toolbar.urls))]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "navbar.html" %}

<body>
  <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>
    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

templates/checkout-page.html
{% extends "base.html" %}

{% block content %}

  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form class="card-body">

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                  <!--firstName-->
                  <div class="md-form ">
                    <input type="text" id="firstName" class="form-control">
                    <label for="firstName" class="">First name</label>
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                  <!--lastName-->
                  <div class="md-form">
                    <input type="text" id="lastName" class="form-control">
                    <label for="lastName" class="">Last name</label>
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <!--Username-->
              <div class="md-form input-group pl-0 mb-5">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="basic-addon1">@</span>
                </div>
                <input type="text" class="form-control py-0" placeholder="Username" aria-describedby="basic-addon1">
              </div>

              <!--email-->
              <div class="md-form mb-5">
                <input type="text" id="email" class="form-control" placeholder="youremail@example.com">
                <label for="email" class="">Email (optional)</label>
              </div>

              <!--address-->
              <div class="md-form mb-5">
                <input type="text" id="address" class="form-control" placeholder="1234 Main St">
                <label for="address" class="">Address</label>
              </div>

              <!--address-2-->
              <div class="md-form mb-5">
                <input type="text" id="address-2" class="form-control" placeholder="Apartment or suite">
                <label for="address-2" class="">Address 2 (optional)</label>
              </div>

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">

                  <label for="country">Country</label>
                  <select class="custom-select d-block w-100" id="country" required>
                    <option value="">Choose...</option>
                    <option>United States</option>
                  </select>
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="state">State</label>
                  <select class="custom-select d-block w-100" id="state" required>
                    <option value="">Choose...</option>
                    <option>California</option>
                  </select>
                  <div class="invalid-feedback">
                    Please provide a valid state.
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="zip">Zip</label>
                  <input type="text" class="form-control" id="zip" placeholder="" required>
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <hr>

              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="same-address">
                <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="save-info">
                <label class="custom-control-label" for="save-info">Save this information for next time</label>
              </div>

              <hr>

              <div class="d-block my-3">
                <div class="custom-control custom-radio">
                  <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" checked required>
                  <label class="custom-control-label" for="credit">Credit card</label>
                </div>
                <div class="custom-control custom-radio">
                  <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="debit">Debit card</label>
                </div>
                <div class="custom-control custom-radio">
                  <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="paypal">Paypal</label>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6 mb-3">
                  <label for="cc-name">Name on card</label>
                  <input type="text" class="form-control" id="cc-name" placeholder="" required>
                  <small class="text-muted">Full name as displayed on card</small>
                  <div class="invalid-feedback">
                    Name on card is required
                  </div>
                </div>
                <div class="col-md-6 mb-3">
                  <label for="cc-number">Credit card number</label>
                  <input type="text" class="form-control" id="cc-number" placeholder="" required>
                  <div class="invalid-feedback">
                    Credit card number is required
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-3 mb-3">
                  <label for="cc-expiration">Expiration</label>
                  <input type="text" class="form-control" id="cc-expiration" placeholder="" required>
                  <div class="invalid-feedback">
                    Expiration date required
                  </div>
                </div>
                <div class="col-md-3 mb-3">
                  <label for="cc-expiration">CVV</label>
                  <input type="text" class="form-control" id="cc-cvv" placeholder="" required>
                  <div class="invalid-feedback">
                    Security code required
                  </div>
                </div>
              </div>
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">3</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Product name</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$12</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Second product</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$8</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Third item</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>$20</strong>
            </li>
          </ul>
          <!-- Cart -->

          <!-- Promo code -->
          <form class="card p-2">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
              </div>
            </div>
          </form>
          <!-- Promo code -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
{% endblock content %}

templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">


  </footer>

templates/home.html
{% extends "base.html" %}

{% block content %}
  <style>
    table.table-sm td, table.table-sm th {
        padding: 1px;
        margin: 0;
        vertical-align: middle;
    }
  </style>
  <main>
    <div class="container-fluid">
      <br>
      <section class="text-center mb-4">
        <!--Grid row-->
        <div class="row wow fadeIn">
          <div class="col-12">
            <table class="table table-hover table-sm">
              <thead class="thead-light">
                <tr>
                  <th>Name</th>
                  <th>Type</th>                
                  <th>Model#</th>
                  <th>Serial#</th>
                  <th>Project</th>
                  <th>Location</th>
                  <!-- <th>Added On</th>
                  <th>Calibrated On</th> -->
                  <th>Remarks</th>
                  <th>Quantity</th>
                  <!-- <th>Slug</th> -->
                  <th></th>
                  <th></th>
                  <th></th>
                </tr>              
              </thead>
              <tbody>
                {% for item in object_list %}
                <tr>
                  <td>{{ item.item_name }}</td>
                  <td>{{ item.item_type }}</td>
                  <td>{{ item.model_num }}</td>
                  <td>{{ item.item_serial_num }}</td>
                  <td>{{ item.project_name }}</td>
                  <td>{{ item.location }}</td>
                  <!-- 
                  <td>{{ item.added_ts }}</td>
                  <td>{{ item.calibration_date }}</td>
                  -->
                  <td>{{ item.remarks }}</td>
                  <td>{{ item.quantity }}</td>
                  <!--<td>{{ item.slug }}</td> -->
                  <td>
                    <a href="{{ item.get_absolute_url }}" class="btn btn-primary btn-sm my-0 p">
                      View
                    </a>
                  </td>
                  <td>
                    <a href="{{ item.get_add_to_cart_url }}" class="btn btn-primary btn-sm my-0 p">
                      Add
                    </a>
                  </td>
                  <td>
                    <a href="{{ item.get_remove_from_cart_url }}" class="btn btn-primary btn-danger btn-sm my-0 p">
                      Remove
                    </a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div> <!-- /col-12 -->
        </div>
        <!--Grid row-->
      </section>
      
      <a href="/add-new-item" type="button" class="btn btn-primary btn-sm" style="width:300px;">
        Add New Item
      </a>
      
      <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <!--Arrow left-->
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}
          <li class="page-item active">
            <a class="page-link" href="?page={{page_obj.number}}">{{page_obj.number}}
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
      <!--Pagination-->
    </div>
  </main>
  <!--Main layout-->  
{% endblock content %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IMS</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <div class="container">
      <h2>Inventory</h2>
      <ul>
        {% for item in items %}
        <li>{{ item.remarks }}</li>
        <li>{{ item.added_ts }}</li>
        <li>{{ item.quantity }}</li>
        <li>{{ item.location }}</li>
        <li>{{ item.item_type }}</li>
        <li>{{ item.item_name }}</li>
        <li>{{ item.model_num }}</li>
        <li>{{ item.project_name }}</li>
        <li>{{ item.item_serial_num }}</li>
        <li>{{ item.calibration_date }}</li>
        {% endfor %}        
      </ul>
      <hr>        
    </div>        
</body>
</html>

templates/landing_page.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container" style="text-align: center;">
      <a href="add-new-item/" type="button" class="btn btn-primary btn-sm" style="width:300px;">
        Add New Item
      </a>
      <a href="home/" type="button" class="btn btn-primary btn-sm" style="width:300px;">
        Go shopping!  
      </a>
    </div>
  </main>
  <!--Main layout-->  
{% endblock content %}

templates/navbar.html
{% load cart_template_tags%}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text">IMS</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          {% comment %} <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/checkout" target="_blank">CheckOut</a>
          </li> {% endcomment %}
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'core:order-summary'%}"  class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{request.user|cart_item_count}} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ user.username }}</span>
            </a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="badge red z-depth-1 mr-1">Logout</span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="badge red z-depth-1 mr-1">Login</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="badge red z-depth-1 mr-1">Signup</span>
            </a>
          </li>
          {% endif %}
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

templates/order_summary.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container-fluid">
      <div class="table-responsive text-nowrap">
        <table class="table table-hover table-sm">
          <thead class="thead-light">
            <tr>
              <th>Name</th>
              <th>Type</th>                
              <th>Model#</th>
              <th>Serial#</th>
              <th>Project</th>
              <th>Location</th>
              <!-- <th>Added On</th>
              <th>Calibrated On</th> -->
              <th>Remarks</th>
              <th>Quantity</th>
              <!-- <th>Slug</th> -->
            </tr>
          </thead>
          <tbody>
          {% for order_item in object.items.all %}
          <tr>
            <td>{{ order_item.item.item_name }}</td>
            <td>{{ order_item.item.item_type }}</td>
            <td>{{ order_item.item.model_num }}</td>
            <td>{{ order_item.item.item_serial_num }}</td>
            <td>{{ order_item.item.project_name }}</td>
            <td>{{ order_item.item.location }}</td>
            <td>{{ order_item.item.remarks }}</td>
            
            <td>
              <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}">
                <i class="fas fa-minus mr-2"></i></a>
              {{ order_item.quantity }}
              <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
              
              <a style="color:red" href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
              </a>
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="5">Your cart is empty</td>
          </tr>
          <tr>
            <td colspan="5">
              <a class="btn btn-primary float-right" href="/">Continue shopping</a>
            </td>
          </tr>
          {% endfor %}
          {% if object.items.all.count > 0 %}
          <tr>
            <td colspan="8">
              <a class="btn btn-sm btn-success float-right ml-2" href="/add-to-inventory">Add to inventory</a>
              <a class="btn btn-sm btn-danger float-right ml-2" href="/delete-from-inventory">Delete from inventory</a>
              <a class="btn btn-sm btn-primary float-left" href="/">Continue shopping!</a>
            </td>
          </tr>
          {% endif %}
          </tbody>
        </table>
      </div>

    </div>
  </main>
  <!--Main layout-->  
{% endblock content %}

templates/product.html
{% extends "base.html" %}
{% block content %}
  <!--Main layout-->
  <main class="">
    <div class="container dark-grey-text">

      <!--Grid row-->
      <div class="row wow fadeIn">

        
        <!--Grid column-->
        <div class="col-6 offset-3">
          <div class="p-4">

            <p class="lead" style="text-transform:uppercase;text-align:center">
              <span>{{ object.item_name }}</span>
            </p>
            <table class="table table-striped table-sm">
              <tr>
                <th style="text-align:right">LOCATION</th>
                <td style="text-align:left">{{ object.location }}</td>
              </tr>
              <tr>
                <th style="text-align:right">ITEM TYPE</th>
                <td style="text-align:left">{{ object.item_type }}</td>
              </tr>
              
              <tr>
                <th style="text-align:right">SERIAL NUMBER</th>
                <td style="text-align:left">{{ object.item_serial_num }}</td>
              </tr>
              <tr>
                <th style="text-align:right">MODEL NUMBER</th>
                <td style="text-align:left">{{ object.model_num }}</td>
              </tr>
              <tr>
                <th style="text-align:right">PROJECT NAME</th>
                <td style="text-align:left">{{ object.project_name }}</td>
              </tr>
              <tr>
                <th style="text-align:right">CALIBRATION DATE</th>
                <td style="text-align:left">{{ object.calibration_date }}</td>
              </tr>
              <tr>
                <th style="text-align:right">ADDED DATE</th>
                <td style="text-align:left">{{ object.added_ts }}</td>
              </tr>
              <tr>
                <th style="text-align:right">REMARKS</th>
                <td style="text-align:left">{{ object.remarks }}</td>
              </tr>
              <tr>
                <th style="text-align:right">REMARKS</th>
                <td style="text-align:left">{{ object.remarks }}</td>
              </tr>
                
              </table>
            <div  style="text-align:center">
            <a  href="{{ object.get_add_to_cart_url }}" 
                class="btn btn-primary btn-sm my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a  href="{{ object.get_remove_from_cart_url }}" 
                class="btn btn-primary btn-danger btn-sm my-0 p">
              Remove from cart
            </a>
            </div>

          </div>
          <!--Content-->

        </div>
      
      <hr>

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
  {% endblock content %}
  

templates/scripts.html
{% load static %}
  
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>